server:
   port: 0
   
spring:

   # Profile for USER-SERVICE.yml/properties in GitHub Config Repo
   profiles:
      active: USER-SERVICE
   # Instead of bootstrap.yml
   config:
      import: "optional:configserver:http://localhost:8888"
   application:
      name: USER-SERVICE
   devtools:
      restart:
         enabled: true
   h2:
      console:
         enabled: true
         settings:
            web-allow-others: true
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: 1
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: update
         
   rabbitmq:
     host: localhost
#     port: 15672
     port: 5672
     username: guest
     password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      hostname: localhost
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
gateway:
   ip: 192.168.1.186
   
token:
   # 10 days
   expiration_time: 864000000
   secret: heyN0w619
   
# For actuator
management:
   endpoints:
      web:
         exposure:
            include: mappings   
   
# For actuator refresh posts - Doesn't work outside of Config Server - ?
#management:
#   endpoints:
#      web:
#         exposure:
#            include: busrefresh   
